<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>True</UseWindowsForms>
    <ApplicationIcon>CatWarsImages_E52D65C7.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="CatWarsImages_E52D65C7.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp" Version="3.9.4" />
    <PackageReference Include="LibVLCSharp.WPF" Version="3.9.4" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.21" />
  </ItemGroup>

</Project>
